# Generated by Django 4.1.11 on 2023-09-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwordHash',
            new_name='password',
        ),
    ]
