# Generated by Django 4.1.11 on 2023-09-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_passwordhash_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='passwordHash',
        ),
    ]
