# Generated by Django 4.1.11 on 2023-09-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='img.jpeg', upload_to='image/%Y', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
